### ISSUE TITLE
using python %%sbash variable outside of remote server

### ISSUE THREAD

**Issue by Sutyke** [auneri/ipyslurm#5]
Thanks a lot for ipyslurm, it's great package. I'm trying to get variable form $$sbatch or $$sbash to use it further in jupyter notebook code. I believe you could expand bit more examples to show how powerful the package is. 

Is there a way to get string variable from remote server , for further use in local ipython?

I'm looking for 2 cases:

1)  
%%sbatch
echo "string"

or

2)
 %%sbash
#!/usr/bin/env python
import pandas as pd
string = pd.read_csv("file.csv")

I woul like to use string variable further in the code outside of %%sbatch or  %%sbash.

It will be great if you can include example if possible.

**Comment by auneri** [comment]
Hello, thanks for the very useful suggestions! Sorry for the late response, the email notification seems to have been filtered by my client.

While the exact functionality you described is not currently available, one possible workaround for the 2nd case would be to use the `--stdout` argument to serialize your output:
```
%%sbash --stdout output
#!/usr/bin/env python
import pandas as pd
string = pd.read_csv("file.csv")
print('string = {}'.format(string))
```

and in the following cell:
```stdout
for line in output:
    exec(line)
```

You can use slurm log files to similarly serialize and parse variables when using `%%sbatch`.

Of course these are both crude workarounds. I will look into a solution that properly reads/writes into the local scope.

**Comment by auneri** [comment]
Hi there! After a long hiatus, the new v2.1 release should better address this issue.

Checkout https://github.com/auneri/ipyslurm/blob/v2.1.0/examples/slurm.ipynb to see an example on how to use the interface directly from Python (without the use of IPython magic functions). While the local and remote scopes are not shared, you can more easily process the input/output to bash commands and sbatch scripts to achieve what you want.
