### ISSUE TITLE
BadAuthenticationType error when try to login

### ISSUE THREAD

**Issue by esmexx** [auneri/ipyslurm#6]
After conda installing ipyslurm and loading the extension as instructed in the tutorial notebook, I ran into BadAuthenticationType error when try to log in a server with my username.

ps: when i wrote both username and password explicitly then I can complete the login, so I think the issue is with the interactive request of password?

**Comment by esmexx** [comment]
ps: when i wrote both username and password explicitly then I can complete the login

**Comment by auneri** [comment]
I think 3d396b9360d18b17d31e27fb21383a8b70d86276 should fix your problem. If you don't want to wait for a release you can install the latest master with:
```
pip install git+https://github.com/auneri/ipyslurm.git@master
```

**Comment by esmexx** [comment]
Awesome! the latest master is working. Thank you

**Comment by auneri** [comment]
👍
